### ISSUE TITLE
Löschen?

### ISSUE THREAD

**Issue by pehbehbeh** [octus83/AP-HA-WS12-13#1]
Ich glaube, das Repo hier kann mal gelöscht werden... ;-)

**Comment by octus83** [comment]
Nein

**Comment by octus83** [comment]
Ich will vorher nochmal pullen

Von meinem Samsung Galaxy Smartphone gesendet.

-------- Ursprüngliche Nachricht --------
Von: Phil-Bastian Berndt notifications@github.com 
Datum:27.01.2015  22:56  (GMT+01:00) 
An: octus83/AP-HA-WS12-13 AP-HA-WS12-13@noreply.github.com 
Cc: Marcus Pfingsten p83@hotmail.de 
Betreff: Re: [AP-HA-WS12-13] Löschen? (#1) 

Closed #1.
